site_name: Sceptile380's Workspace
site_url: https://mydomain.org/mysite

theme:
  name: material
  palette:
    - media: (min-width: 768px)
      name: light
      primary: "#FF5733"
      accent: "#33C1FF"
      background: "#F1F1F1"
    - media: (max-width: 767px)
      name: dark
      primary: "#1A237E"
      accent: "#FF4081"
      background: "#121212"

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tab.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - blog
  - tags:
      tags_file: tags.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About:
      - About Me: about/about.md
      - Skibidi Sigma: about/lol.md
  - Red Angry Birds: spinning_bouncing.html
  - bouncy armadillo: armadillo.md
  - Code Docs:
      - Java: coding/java_1.md
  - Tags: tags.md
  - Blog:
      - blog/index.md
