site_name: Sceptile380's Workspace
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: assets/s380_minilogo.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tab.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - blog
  - mkdocs-video
  - tags:
     tags_file: tags.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Tags: tags.md
  - About:
    - About Me: about/about.md
    - 3D Artworks: about/3d_art.md
    - Digital Art & Graphics: about/art_n_graph.md
  - Red Angry Birds: spinning_bouncing.html
  - Blog:
    - blog/index.md
  - Code Docs:
    - Java: coding/java_1.md
